type Token = string;

export const getClassName = (tag: string, className?: string) =>
  `mickey-${tag} ${className ? className : ""}`;

export const resolve = (cssVar: string) =>
  getComputedStyle(document.documentElement).getPropertyValue(cssVar).trim();

export const styles = {
  color: {
    disabled: {
      text: "var(--color-neutral-600)",
      icon: "var(--color-neutral-400)",
      background: "var(--color-neutral-200)",
      onBackground: "var(--color-neutral-400)",
      border: "var(--color-neutral-500)",
    },
    primary: {
      main: "var(--color-primary-main)",
      contrast: "var(--color-primary-contrast)",
      light: "var(--color-primary-light)",
      dark: "var(--color-primary-dark)",
      palette: {
        50: "var(--color-primary-50)",
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        400: "var(--color-primary-400)",
        500: "var(--color-primary-500)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
      },
    },
    secondary: {
      main: "var(--color-secondary-main)",
      contrast: "var(--color-secondary-contrast)",
      light: "var(--color-secondary-light)",
      dark: "var(--color-secondary-dark)",
      palette: {
        50: "var(--color-secondary-50)",
        100: "var(--color-secondary-100)",
        200: "var(--color-secondary-200)",
        300: "var(--color-secondary-300)",
        400: "var(--color-secondary-400)",
        500: "var(--color-secondary-500)",
        600: "var(--color-secondary-600)",
        700: "var(--color-secondary-700)",
        800: "var(--color-secondary-800)",
        900: "var(--color-secondary-900)",
      },
    },
    error: {
      main: "var(--color-error-main)",
      light: "var(--color-error-light)",
      contrast: "var(--color-error-contrast)",
      palette: {
        50: "var(--color-error-50)",
        100: "var(--color-error-100)",
        200: "var(--color-error-200)",
        300: "var(--color-error-300)",
        400: "var(--color-error-400)",
        500: "var(--color-error-500)",
        600: "var(--color-error-600)",
        700: "var(--color-error-700)",
        800: "var(--color-error-800)",
        900: "var(--color-error-900)",
      },
    },
    warning: {
      main: "var(--color-warning-main)",
      light: "var(--color-warning-light)",
      contrast: "var(--color-warning-contrast)",
      palette: {
        50: "var(--color-warning-50)",
        100: "var(--color-warning-100)",
        200: "var(--color-warning-200)",
        300: "var(--color-warning-300)",
        400: "var(--color-warning-400)",
        500: "var(--color-warning-500)",
        600: "var(--color-warning-600)",
        700: "var(--color-warning-700)",
        800: "var(--color-warning-800)",
        900: "var(--color-warning-900)",
      },
    },
    info: {
      main: "var(--color-info-main)",
      light: "var(--color-info-light)",
      contrast: "var(--color-info-contrast)",
      palette: {
        50: "var(--color-info-50)",
        100: "var(--color-info-100)",
        200: "var(--color-info-200)",
        300: "var(--color-info-300)",
        400: "var(--color-info-400)",
        500: "var(--color-info-500)",
        600: "var(--color-info-600)",
        700: "var(--color-info-700)",
        800: "var(--color-info-800)",
        900: "var(--color-info-900)",
      },
    },
    success: {
      main: "var(--color-success-main)",
      light: "var(--color-success-light)",
      contrast: "var(--color-success-contrast)",
      palette: {
        50: "var(--color-success-50)",
        100: "var(--color-success-100)",
        200: "var(--color-success-200)",
        300: "var(--color-success-300)",
        400: "var(--color-success-400)",
        500: "var(--color-success-500)",
        600: "var(--color-success-600)",
        700: "var(--color-success-700)",
        800: "var(--color-success-800)",
        900: "var(--color-success-900)",
      },
    },
    neutral: {
      0: "var(--color-neutral-0)",
      50: "var(--color-neutral-50)",
      100: "var(--color-neutral-100)",
      200: "var(--color-neutral-200)",
      300: "var(--color-neutral-300)",
      400: "var(--color-neutral-400)",
      500: "var(--color-neutral-500)",
      600: "var(--color-neutral-600)",
      700: "var(--color-neutral-700)",
      800: "var(--color-neutral-800)",
      900: "var(--color-neutral-900)",
      1000: "var(--color-neutral-1000)",
    },
  },
  surface: {
    bg: "var(--surface-bg)",
    paper: "var(--surface-paper)",
    border: {
      custom: {
        color: {
          light: "var(--surface-border)",
          dark: "var(--surface-border-dark)",
        },
        style: {
          solid: "solid",
          dotted: "dotted",
          dashed: "dashed",
        },
        width: {
          sm: "1px",
          md: "2px",
          lg: "3px",
          xl: "4px",
        },
      },
      default: {
        solidDarkThin: "1px solid var(--surface-border-dark)",
        solidLightThin: "1px solid var(--surface-border)",
        solidDarkMd: "1px solid var(--surface-border-dark)",
        solidLightMd: "1px solid var(--surface-border)",
        dashedDarkThin: "1px dashed var(--surface-border-dark)",
        dashedLightThin: "1px dashed var(--surface-border)",
        dashedDarkMd: "1px dashed var(--surface-border-dark)",
        dashedLightMd: "1px dashed var(--surface-border)",
        dottedDarkThin: "1px dotted var(--surface-border-dark)",
        dottedLightThin: "1px dotted var(--surface-border)",
        dottedDarkMd: "1px dotted var(--surface-border-dark)",
        dottedLightMd: "1px dotted var(--surface-border)",
      },
    },
    divider: "var(--divider)",
  },
  text: {
    primary: "var(--text-primary)",
    secondary: "var(--text-secondary)",
    placeholder: "var(--color-neutral-600)",
    disabled: "var(--text-disabled)",
  },
  typography: {
    family: "var(--font-family-sans)",
    weight: {
      regular: "var(--font-weight-regular)",
      medium: "var(--font-weight-medium)",
      bold: "var(--font-weight-bold)",
    },
    size: {
      h1: "var(--font-size-h1)",
      h2: "var(--font-size-h2)",
      h3: "var(--font-size-h3)",
      h4: "var(--font-size-h4)",
      h5: "var(--font-size-h5)",
      h6: "var(--font-size-h6)",
      subtitle1: "var(--font-size-subtitle1)",
      subtitle2: "var(--font-size-subtitle2)",
      body1: "var(--font-size-body1)",
      body2: "var(--font-size-body2)",
      button: "var(--font-size-button)",
      caption: "var(--font-size-caption)",
      overline: "var(--font-size-overline)",
    },
    lineHeight: {
      h1: "var(--line-height-h1)",
      h2: "var(--line-height-h2)",
      h3: "var(--line-height-h3)",
      h4: "var(--line-height-h4)",
      h5: "var(--line-height-h5)",
      h6: "var(--line-height-h6)",
      subtitle1: "var(--line-height-subtitle1)",
      subtitle2: "var(--line-height-subtitle2)",
      body1: "var(--line-height-body1)",
      body2: "var(--line-height-body2)",
      button: "var(--line-height-button)",
      caption: "var(--line-height-caption)",
      overline: "var(--line-height-overline)",
    },
    tracking: {
      h1: "var(--tracking-h1)",
      h2: "var(--tracking-h2)",
      h3: "var(--tracking-h3)",
      h4: "var(--tracking-h4)",
      h5: "var(--tracking-h5)",
      h6: "var(--tracking-h6)",
      subtitle1: "var(--tracking-subtitle1)",
      subtitle2: "var(--tracking-subtitle2)",
      body1: "var(--tracking-body1)",
      body2: "var(--tracking-body2)",
      button: "var(--tracking-button)",
      caption: "var(--tracking-caption)",
      overline: "var(--tracking-overline)",
    },
  },

  spacing: {
    unit: "var(--space-unit)",
    tiny: "1px",
    xxs: "var(--space-0)",
    xs: "var(--space-1)",
    sm: "var(--space-2)",
    md: "var(--space-3)",
    lg: "var(--space-4)",
    xl: "var(--space-5)",
    "2xl": "var(--space-6)",
    "3xl": "var(--space-8)",
    "4xl": "var(--space-10)",
    // numeric indices if you prefer styles.spacing[4]
    0: "var(--space-0)" as Token,
    1: "var(--space-1)" as Token,
    2: "var(--space-2)" as Token,
    3: "var(--space-3)" as Token,
    4: "var(--space-4)" as Token,
    5: "var(--space-5)" as Token,
    6: "var(--space-6)" as Token,
    8: "var(--space-8)" as Token,
    10: "var(--space-10)" as Token,
  },

  radius: {
    none: "var(--radius-none)",
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    pill: "var(--radius-pill)",
  },

  shadow: {
    0: "var(--shadow-0)",
    1: "var(--shadow-1)",
    2: "var(--shadow-2)",
    3: "var(--shadow-3)",
    4: "var(--shadow-4)",
    6: "var(--shadow-6)",
    8: "var(--shadow-8)",
    12: "var(--shadow-12)",
    16: "var(--shadow-16)",
    24: "var(--shadow-24)",
  },

  breakpoint: {
    xs: "var(--breakpoint-xs)",
    sm: "var(--breakpoint-sm)",
    md: "var(--breakpoint-md)",
    lg: "var(--breakpoint-lg)",
    xl: "var(--breakpoint-xl)",
  },

  container: {
    sm: "var(--container-sm)",
    md: "var(--container-md)",
    lg: "var(--container-lg)",
    xl: "var(--container-xl)",
  },

  zIndex: {
    appbar: "var(--z-index-appbar)",
    drawer: "var(--z-index-drawer)",
    modal: "var(--z-index-modal)",
    snackbar: "var(--z-index-snackbar)",
    tooltip: "var(--z-index-tooltip)",
    top: "var(--z-index-top)",
  },

  transition: {
    easing: {
      easeInOut: "var(--easing-ease-in-out)",
      easeOut: "var(--easing-ease-out)",
      easeIn: "var(--easing-ease-in)",
      sharp: "var(--easing-sharp)",
    },
    duration: {
      shortest: "var(--duration-shortest)",
      shorter: "var(--duration-shorter)",
      short: "var(--duration-short)",
      standard: "var(--duration-standard)",
      complex: "var(--duration-complex)",
      entering: "var(--duration-entering-screen)",
      leaving: "var(--duration-leaving-screen)",
    },
  },
} as const;
